Repository Hous-Release/hous-server, pull requests merged in 2022-11, with the labels that each got.

#202 #201 [fix] 방 퇴사 로직 수정
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/room/RoomServiceUtils.java
  src/main/java/hous/server/service/user/UserService.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#204 [fix] 회원탈퇴 시 feedback을 받고 저장하도록 수정
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/domain/feedback/Feedback.java
  src/main/java/hous/server/domain/feedback/FeedbackType.java
  src/main/java/hous/server/domain/feedback/repository/FeedbackRepository.java
  src/main/java/hous/server/domain/feedback/repository/FeedbackRepositoryCustom.java
  src/main/java/hous/server/domain/feedback/repository/FeedbackRepositoryImpl.java
  src/main/java/hous/server/service/slack/dto/response/UserDeleteResponse.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/dto/request/DeleteUserRequestDto.java
  src/main/resources/messages/validation.properties
Labels: 🐣 혜정 🐣, 🔧 Fix

#206 탈퇴 시 피드백 값이 존재할 경우에만 디비에 저장되도록 수정
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/domain/feedback/Feedback.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/dto/request/DeleteUserRequestDto.java
  src/main/resources/messages/validation.properties
Labels: 🐣 혜정 🐣, 🔧 Fix

#210 사용자 정보 조회/수정 api 수정
  src/main/java/hous/server/common/util/DateUtils.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/controller/user/UserRetrieveController.java
  src/main/java/hous/server/service/user/dto/request/UpdateUserInfoRequestDto.java
  src/main/java/hous/server/service/user/dto/response/UserInfoResponse.java
  src/main/resources/messages/validation.properties
Labels: 🐣 혜정 🐣, 🔧 Fix

#212 #209 [fix] 로그인 fcmToken 중복 관련 트랜잭션 이슈 해결
  src/main/java/hous/server/service/auth/CommonAuthService.java
  src/main/java/hous/server/service/auth/CommonAuthServiceUtils.java
  src/main/java/hous/server/service/auth/impl/AppleAuthService.java
  src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#217 #216 [fix] 회원가입시 fcmToken 중복 관련 이슈 해결
  src/main/java/hous/server/service/auth/impl/AppleAuthService.java
  src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#219 사용자 관련 Api 수정
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/domain/common/Constraint.java
  src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
  src/main/java/hous/server/service/todo/dto/response/TodoInfoResponse.java
  src/main/java/hous/server/service/todo/dto/response/UserPersonalityInfoResponse.java
  src/main/java/hous/server/service/user/dto/request/DeleteUserRequestDto.java
  src/main/resources/messages/validation.properties
Labels: 🐣 혜정 🐣, 🔧 Fix

#221 #220 [fix] 온보딩 introduction 필드 수정
  src/main/java/hous/server/domain/user/Onboarding.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#223 [fix] 자기소개에서 \n 입력 시 공백으로 치환하여 저장하도록 수정
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/controller/user/UserRetrieveController.java
  src/main/java/hous/server/domain/user/Onboarding.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#226 #225 [fix] 푸시 알림 워딩 집 Rules -> 첫 Rules로 변경
  src/main/java/hous/server/domain/badge/BadgeInfo.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#232 #231 [feat] 사용자 탈퇴 시 슬랙 알림 구현
  src/main/java/hous/server/controller/advice/ControllerExceptionAdvice.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/service/slack/SlackService.java
  src/main/java/hous/server/service/slack/SlackServiceUtils.java
  src/main/java/hous/server/service/slack/dto/response/UserDelete.java
  src/main/java/hous/server/service/slack/dto/response/UserDeleteResponse.java
  src/main/java/hous/server/service/user/UserRetrieveService.java
Labels: ✨ Feature, 🐣 혜정 🐣

#237 #235 [fix] 멤버별 조회 시 todo Cnt 개수 수정
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/service/rule/RuleService.java
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#236 #234 [fix] 규칙 수정 시 규칙에 대한 validate 추가
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/service/rule/RuleService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#239 #238 [fix] ourtodoinfo 가공 시 sorted(Onboarding::compareTo) 추가
  src/main/java/hous/server/service/home/HomeRetrieveService.java
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
  src/main/java/hous/server/service/todo/dto/response/OurTodo.java
  src/main/java/hous/server/service/todo/dto/response/OurTodoInfo.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#241 #240 [fix] 요일별 조회 시 OurTodo에 todoId를 넘겨주도록 수정
  src/main/java/hous/server/service/home/HomeRetrieveService.java
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
  src/main/java/hous/server/service/todo/dto/response/OurTodo.java
  src/main/java/hous/server/service/todo/dto/response/OurTodoInfo.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#243 #242 [fix] 생성한 todo의 알림 설정 여부도 추가
  src/main/java/hous/server/service/notification/NotificationService.java
  src/main/java/hous/server/service/todo/TodoScheduledService.java
  src/main/java/hous/server/service/todo/TodoServiceUtils.java
Labels: 🐣 혜정 🐣, 🔧 Fix
