Repository Hous-Release/hous-server, pull requests merged in 2022-12, with the labels that each got.

#246 규칙, todo 추가/수정 시 이미 존재하는 name인 경우 409를 던지도록 수정
  src/main/java/hous/server/common/exception/ErrorCode.java
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/controller/todo/TodoController.java
  src/main/java/hous/server/service/rule/RuleService.java
  src/main/java/hous/server/service/rule/RuleServiceUtils.java
  src/main/java/hous/server/service/todo/TodoService.java
  src/main/java/hous/server/service/todo/TodoServiceUtils.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#248 #247 [comment] 이번 릴리즈 때 규칙 추가/수정 시 name 중복 여부는 없애기로 변경되어 주석처리
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/service/rule/RuleService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#250 Redis를 이용하여 중복 요청 방지하는 로직 추가
  build.gradle
  src/main/java/hous/server/common/aspect/PreventDuplicateRequest.java
  src/main/java/hous/server/common/aspect/RequestAspect.java
  src/main/java/hous/server/common/exception/ErrorCode.java
  src/main/java/hous/server/config/WebConfig.java
  src/main/java/hous/server/config/interceptor/auth/Auth.java
  src/main/java/hous/server/config/interceptor/auth/AuthInterceptor.java
  src/main/java/hous/server/config/interceptor/auth/LoginCheckHandler.java
  src/main/java/hous/server/config/interceptor/version/Version.java
  src/main/java/hous/server/config/interceptor/version/VersionCheckHandler.java
  src/main/java/hous/server/config/interceptor/version/VersionInterceptor.java
  src/main/java/hous/server/config/resolver/UserIdResolver.java
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/controller/home/HomeRetrieveController.java
  src/main/java/hous/server/controller/room/RoomController.java
  src/main/java/hous/server/controller/room/RoomRetrieveController.java
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/controller/rule/RuleRetrieveController.java
  src/main/java/hous/server/controller/todo/TodoController.java
  src/main/java/hous/server/controller/todo/TodoRetrieveController.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/controller/user/UserRetrieveController.java
  src/main/java/hous/server/domain/common/RedisKey.java
  src/main/java/hous/server/service/todo/TodoService.java
Labels: ✨ Feature, 🐣 혜정 🐣, 🐼 혁준 🐼

#251 #249 [fix] 퇴사 로직 todo 및 방 퇴사 로직 수정, personality gray로 변경하도록 수정
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/room/RoomServiceUtils.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#253 #252 [fix] AfterReturning -> After 로 수정
  src/main/java/hous/server/common/aspect/RequestAspect.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#255 #254 [fix] todo 수정시 수정하는 todo 제외하고 이름 검사하도록 수정
  src/main/java/hous/server/service/todo/TodoService.java
  src/main/java/hous/server/service/todo/TodoServiceUtils.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#257 #256 [fix] Todo 멤버별, 요일별 조회에 방 총 todo 개수 필드 추가
  src/main/java/hous/server/controller/todo/TodoRetrieveController.java
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
  src/main/java/hous/server/service/todo/dto/response/TodoAllDayInfo.java
  src/main/java/hous/server/service/todo/dto/response/TodoAllDayResponse.java
  src/main/java/hous/server/service/todo/dto/response/TodoAllMemberInfo.java
  src/main/java/hous/server/service/todo/dto/response/TodoAllMemberResponse.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#259 #258 [feat] 강제 업데이트 관련 api 구현
  src/main/java/hous/server/common/success/SuccessCode.java
  src/main/java/hous/server/config/interceptor/version/VersionCheckHandler.java
  src/main/java/hous/server/controller/version/VersionRetrieveController.java
  src/main/java/hous/server/domain/deploy/Deploy.java
  src/main/java/hous/server/service/version/VersionRetrieveService.java
  src/main/java/hous/server/service/version/VersionServiceUtils.java
  src/main/java/hous/server/service/version/dto/response/VersionInfoResponse.java
Labels: ✨ Feature, 🐼 혁준 🐼

#261 #260 [fix] 방퇴사, 탈퇴시 나의 todo 삭제 관련 수정
  src/main/java/hous/server/service/room/RoomServiceUtils.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#265 사용하지 않는 디펜던시를 삭제하고, 자잘한 수정
  build.gradle
  src/main/java/hous/server/service/todo/TodoScheduledService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#267 버전 관리 로직 반영
  src/main/java/hous/server/config/WebConfig.java
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/controller/home/HomeRetrieveController.java
  src/main/java/hous/server/controller/room/RoomController.java
  src/main/java/hous/server/controller/room/RoomRetrieveController.java
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/controller/rule/RuleRetrieveController.java
  src/main/java/hous/server/controller/todo/TodoController.java
  src/main/java/hous/server/controller/todo/TodoRetrieveController.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/controller/user/UserRetrieveController.java
Labels: 🌏 Deploy, 🐼 혁준 🐼

#272 #271 [fix] 탈퇴 유저 알림 슬랙에 의견 추가
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/service/slack/SlackService.java
  src/main/java/hous/server/service/slack/SlackServiceUtils.java
  src/main/java/hous/server/service/slack/dto/response/UserDeleteResponse.java
  src/main/java/hous/server/service/user/UserRetrieveService.java
  src/main/java/hous/server/service/user/UserService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#276 #275 [!HOTFIX] 방장이 방을 나가면 방장이 다음 참여자로 바뀌도록 로직 수정
  src/main/java/hous/server/domain/room/Room.java
  src/main/java/hous/server/service/room/RoomServiceUtils.java
Labels: 🐞 HotFix, 🐼 혁준 🐼

#277 release 1.0.1
  src/main/java/hous/server/domain/room/Room.java
  src/main/java/hous/server/service/room/RoomServiceUtils.java
Labels: 🌏 Deploy, 🐣 혜정 🐣, 🐼 혁준 🐼

#279 방 퇴사 시 알림 목록 삭제하는 로직 수정
  build.gradle
  src/main/java/hous/server/config/swagger/SwaggerConfig.java
  src/main/java/hous/server/domain/user/Onboarding.java
  src/main/java/hous/server/service/room/RoomService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#281 사용자 탈퇴 요청 시 피드백 받는 부분 수정
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/service/slack/SlackServiceUtils.java
  src/main/java/hous/server/service/slack/dto/response/UserDeleteResponse.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
  src/main/java/hous/server/service/user/dto/request/DeleteUserRequestDto.java
  src/main/resources/messages/validation.properties
Labels: 🐣 혜정 🐣, 🔧 Fix

#284 전체적으로 생년월일 optional 하게 처리하도록 수정
  src/main/java/hous/server/common/exception/ErrorCode.java
  src/main/java/hous/server/common/util/DateUtils.java
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/controller/auth/dto/request/SignUpRequestDto.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/domain/user/Onboarding.java
  src/main/java/hous/server/domain/user/repository/UserRepositoryCustom.java
  src/main/java/hous/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/hous/server/service/auth/dto/request/SignUpDto.java
  src/main/java/hous/server/service/user/UserScheduledService.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
  src/main/java/hous/server/service/user/dto/request/CreateUserRequestDto.java
  src/main/java/hous/server/service/user/dto/request/UpdateUserInfoRequestDto.java
  src/main/java/hous/server/service/user/dto/response/UserInfoResponse.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#288 release 1.0.4
  build.gradle
  src/main/java/hous/server/config/swagger/SwaggerConfig.java
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
  src/main/java/hous/server/service/todo/TodoServiceUtils.java
Labels: 🌏 Deploy, 🐣 혜정 🐣, 🐼 혁준 🐼
