Repository Hous-Release/hous-server, pull requests merged in 2022-09, with the labels that each got.

#105 스케줄 서비스, 배지 획득 로직 리팩토링
  src/main/java/hous/server/service/badge/BadgeService.java
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/rule/RuleService.java
  src/main/java/hous/server/service/todo/TodoScheduledService.java
  src/main/java/hous/server/service/todo/TodoService.java
  src/main/java/hous/server/service/user/UserService.java
Labels: 🐼 혁준 🐼, 🔨 Refactor

#112 #110 [fix] 배지 설명 문구 수정
  src/main/java/hous/server/domain/badge/BadgeInfo.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#114 회원 정보 탈퇴 api 구현 및 수정
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/domain/notification/Notification.java
  src/main/java/hous/server/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/hous/server/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/hous/server/domain/user/Onboarding.java
  src/main/java/hous/server/service/notification/NotificationService.java
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/room/RoomServiceUtils.java
  src/main/java/hous/server/service/user/UserService.java
Labels: ✨ Feature, 🐣 혜정 🐣, 🔧 Fix

#116 #111 [fix] User 테이블 수정 및 fcmToken 중복 검사 로직 추가
  src/main/java/hous/server/common/exception/ErrorCode.java
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/domain/user/User.java
  src/main/java/hous/server/service/auth/impl/AppleAuthService.java
  src/main/java/hous/server/service/auth/impl/KaKaoAuthService.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#115 todo 관련 푸시알림 구현
  src/main/java/hous/server/domain/notification/PushMessage.java
  src/main/java/hous/server/service/notification/NotificationService.java
  src/main/java/hous/server/service/todo/TodoScheduledService.java
  src/main/java/hous/server/service/todo/TodoService.java
Labels: ✨ Feature, 🐼 혁준 🐼

#121 #118 [fix] 푸시 알림 설정 수정 기능 PATCH 메소드로 수정
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/domain/user/Setting.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
  src/main/java/hous/server/service/user/dto/request/UpdatePushSettingRequestDto.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#120 피드백 한걸음 뱃지 api 구현
  src/main/java/hous/server/common/success/SuccessCode.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/user/UserService.java
Labels: ✨ Feature, 🐣 혜정 🐣

#125 #124 [fix] 로그 레벨 분리
  src/main/java/hous/server/controller/advice/ControllerExceptionAdvice.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#127 호미의 탄생 배지 구현
  src/main/java/hous/server/domain/user/repository/UserRepositoryCustom.java
  src/main/java/hous/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/hous/server/service/user/UserScheduledService.java
Labels: ✨ Feature, 🐣 혜정 🐣

#123 로그아웃 기능 구현
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/domain/user/User.java
  src/main/java/hous/server/service/auth/AuthServiceProvider.java
  src/main/java/hous/server/service/auth/CommonAuthService.java
  src/main/java/hous/server/service/auth/CreateTokenService.java
  src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
  src/main/java/hous/server/service/firebase/FirebaseCloudMessageService.java
Labels: ✨ Feature, 🐼 혁준 🐼

#132 #131 [fix] fcmToken null 인 경우 에러 해결
  src/main/java/hous/server/service/firebase/FirebaseCloudMessageService.java
  src/main/java/hous/server/service/notification/NotificationService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#134 #133 [fix] 애플 로그인 에러 핸들링 추가
  src/main/java/hous/server/common/exception/UnAuthorizedException.java
  src/main/java/hous/server/external/client/apple/AppleTokenProviderImpl.java
Labels: 🐣 혜정 🐣, 🐼 혁준 🐼, 🔧 Fix

#142 규칙 추가 api 여러개의 규칙 생성 가능하도록 수정
  src/main/java/hous/server/common/exception/ErrorCode.java
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/domain/room/Room.java
  src/main/java/hous/server/service/notification/NotificationService.java
  src/main/java/hous/server/service/rule/RuleService.java
  src/main/java/hous/server/service/rule/RuleServiceUtils.java
  src/main/java/hous/server/service/rule/dto/request/CreateRuleRequestDto.java
  src/main/java/hous/server/service/rule/dto/request/ModifyRuleReqeustDto.java
  src/main/resources/messages/validation.properties
Labels: ✨ Feature, 🐣 혜정 🐣

#144 #143 [fix] 배지 테이블, enum 수정
  src/main/java/hous/server/domain/badge/Badge.java
  src/main/java/hous/server/domain/badge/BadgeInfo.java
  src/main/java/hous/server/service/user/dto/response/MyBadgeInfoResponse.java
  src/main/java/hous/server/service/user/dto/response/RepresentBadgeInfo.java
  src/main/java/hous/server/service/user/dto/response/UserInfoResponse.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#146 #139 [refactor] 길이, 크기 제한 관련 리팩토링
  src/main/java/hous/server/controller/auth/dto/request/SignUpRequestDto.java
  src/main/java/hous/server/domain/common/Constraint.java
  src/main/java/hous/server/domain/room/repository/ParticipateRepositoryCustom.java
  src/main/java/hous/server/domain/room/repository/ParticipateRepositoryImpl.java
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/room/RoomServiceUtils.java
  src/main/java/hous/server/service/room/dto/request/SetRoomNameRequestDto.java
  src/main/java/hous/server/service/rule/RuleServiceUtils.java
  src/main/java/hous/server/service/rule/dto/request/CreateRuleRequestDto.java
  src/main/java/hous/server/service/rule/dto/request/ModifyRuleReqeustDto.java
  src/main/java/hous/server/service/rule/dto/request/UpdateRuleRequestDto.java
  src/main/java/hous/server/service/todo/TodoServiceUtils.java
  src/main/java/hous/server/service/todo/dto/request/TodoInfoRequestDto.java
  src/main/java/hous/server/service/user/dto/request/UpdateTestScoreRequestDto.java
  src/main/java/hous/server/service/user/dto/request/UpdateUserInfoRequestDto.java
  src/main/resources/messages/validation.properties
Labels: 🐼 혁준 🐼, 🔨 Refactor

#148 #147 [fix] 스케줄러 관련 에러 핸들링 추가
  src/main/java/hous/server/config/scheduler/SchedulerConfig.java
  src/main/java/hous/server/config/scheduler/SchedulerErrorHandler.java
Labels: 🐣 혜정 🐣, 🐼 혁준 🐼, 🔧 Fix
