Repository Hous-Release/hous-server, pull requests merged in 2022-10, with the labels that each got.

#154 #151 [fix] 알림 content enum name으로 저장되는 오류 수정
  src/main/java/hous/server/service/notification/NotificationService.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#155 slack 알림 에러 추가
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
  .gitignore
  build.gradle
  src/main/java/hous/server/common/util/JwtUtils.java
  src/main/java/hous/server/controller/advice/ControllerExceptionAdvice.java
  src/main/java/hous/server/service/slack/SlackService.java
Labels: 🌏 Deploy, 🐣 혜정 🐣

#157 #156 [fix] 홈 조회에 room code 정보 추가
  src/main/java/hous/server/service/home/HomeRetrieveService.java
  src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#159 멤버별 조회 시 todoId도 받도록 수정
  src/main/java/hous/server/service/home/HomeRetrieveService.java
  src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
  src/main/java/hous/server/service/todo/dto/response/DayOfWeekTodo.java
  src/main/java/hous/server/service/todo/dto/response/TodoAllDayResponse.java
  src/main/java/hous/server/service/todo/dto/response/TodoDetailInfo.java
  src/main/java/hous/server/service/todo/dto/response/TodoInfo.java
  src/main/java/hous/server/service/todo/dto/response/TodoMainResponse.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#161 클라 요청에 따라 로그인 요청 시 방 참가여부 함께 전달하도록 수정
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/controller/auth/dto/response/LoginResponse.java
  src/main/java/hous/server/service/room/RoomService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#163 #162 [fix] 신규 배지 표시, 읽음 처리 추가
  src/main/java/hous/server/controller/user/UserRetrieveController.java
  src/main/java/hous/server/domain/badge/Acquire.java
  src/main/java/hous/server/service/user/UserRetrieveService.java
  src/main/java/hous/server/service/user/dto/response/MyBadgeInfoResponse.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#165 호미 정렬, 슬랙 메시지 prod 환경에서만 오도록 수정
  src/main/java/hous/server/domain/room/Participate.java
  src/main/java/hous/server/domain/user/Onboarding.java
  src/main/java/hous/server/domain/user/TestScore.java
  src/main/java/hous/server/service/home/HomeRetrieveService.java
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/slack/SlackService.java
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
  src/main/java/hous/server/service/todo/TodoServiceUtils.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#168 #167 [fix] 방 퇴사할 때 나의 Todo 필터링 추가
  src/main/java/hous/server/service/todo/TodoRetrieveService.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#173 #172 [fix] 토큰 갱신 응답 수정
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/service/auth/CreateTokenService.java
  src/main/java/hous/server/service/auth/dto/response/RefreshResponse.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#178 #176 [feat] 강제 로그인 api 추가
  src/main/java/hous/server/common/exception/ErrorCode.java
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/service/auth/AuthService.java
  src/main/java/hous/server/service/auth/impl/AppleAuthService.java
  src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
Labels: ✨ Feature, 🐼 혁준 🐼

#169 사용자 탈퇴 방 참여 여부에 따라 다르게 수정
  src/main/java/hous/server/controller/todo/TodoRetrieveController.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/service/room/RoomService.java
  src/main/java/hous/server/service/room/RoomServiceUtils.java
  src/main/java/hous/server/service/user/UserService.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#179 로그인 로직 리팩토링, 로그아웃 로직 수정
  src/main/java/hous/server/controller/auth/AuthController.java
  src/main/java/hous/server/service/auth/CommonAuthService.java
  src/main/java/hous/server/service/auth/CommonAuthServiceUtils.java
  src/main/java/hous/server/service/auth/impl/AppleAuthService.java
  src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
Labels: 🐼 혁준 🐼, 🔧 Fix, 🔨 Refactor

#186 성향 테스트 시 수정 성공 response와 함께 변경된 Personality color 전달하도록 수정
  src/main/java/hous/server/common/success/SuccessCode.java
  src/main/java/hous/server/controller/user/UserController.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/UserServiceUtils.java
  src/main/java/hous/server/service/user/dto/response/UpdatePersonalityColorResponse.java
Labels: 🐣 혜정 🐣, 🔧 Fix

#188 규칙 수정 api 1개로 통일
  src/main/java/hous/server/common/exception/ErrorCode.java
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/domain/room/Room.java
  src/main/java/hous/server/domain/rule/Rule.java
  src/main/java/hous/server/service/rule/RuleService.java
  src/main/java/hous/server/service/rule/RuleServiceUtils.java
  src/main/java/hous/server/service/rule/dto/request/DeleteRuleReqeustDto.java
  src/main/java/hous/server/service/rule/dto/request/UpdateRuleRequestDto.java
  src/main/java/hous/server/service/rule/dto/response/RuleInfoResponse.java
  src/main/resources/messages/validation.properties
Labels: 🐣 혜정 🐣, 🔧 Fix

#192 fcm, 규칙 관련 에러핸들링 수정, RuleInfo 리팩토링
  src/main/java/hous/server/controller/rule/RuleController.java
  src/main/java/hous/server/controller/rule/RuleRetrieveController.java
  src/main/java/hous/server/service/firebase/FirebaseCloudMessageService.java
  src/main/java/hous/server/service/rule/RuleRetrieveService.java
  src/main/java/hous/server/service/rule/dto/request/CreateRuleRequestDto.java
  src/main/java/hous/server/service/rule/dto/request/DeleteRuleReqeustDto.java
  src/main/java/hous/server/service/rule/dto/request/UpdateRuleRequestDto.java
  src/main/java/hous/server/service/rule/dto/response/RuleInfo.java
  src/main/java/hous/server/service/rule/dto/response/RuleInfoResponse.java
  src/main/resources/messages/validation.properties
Labels: 🐼 혁준 🐼, 🔧 Fix, 🔨 Refactor

#190 #189 [fix] JWT 관련 에러 핸들링 추가
  src/main/java/hous/server/common/util/JwtUtils.java
Labels: 🐼 혁준 🐼, 🔧 Fix

#194 #193 [fix] 홈 화면 조회 요일 데이터 추가
  src/main/java/hous/server/service/home/HomeRetrieveService.java
  src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
Labels: 🐼 혁준 🐼, 🔧 Fix
