Repository Hous-Release/hous-server, pull requests merged in 2023-04, with the labels that each got.

#313 배지 관련 데이터 mongoDB 적용하는 방식으로 로직 수정
  src/main/java/hous/server/domain/badge/BadgeCounter.java
  src/main/java/hous/server/domain/badge/BadgeCounterType.java
  src/main/java/hous/server/domain/badge/mongo/BadgeCounterRepository.java
  src/main/java/hous/server/service/rule/RuleService.java
  src/main/java/hous/server/service/todo/TodoScheduledService.java
  src/main/java/hous/server/service/user/UserService.java
  src/main/java/hous/server/service/user/dto/request/UpdateTestScoreRequestDto.java
  src/test/java/hous/server/service/badge/BadgeServiceTest.java
  src/test/java/hous/server/service/badge/BadgeServiceUtilsTest.java
  src/test/java/hous/server/service/todo/TodoServiceTest.java
Labels: ✨ Feature, ✅ Test, 🐣 혜정 🐣, 🔧 Fix

#322 external api 모듈 분리
  .github/workflows/api-deploy-dev.yml
  .github/workflows/api-deploy-prod.yml
  .github/workflows/api-pr-check-dev.yml
  .github/workflows/api-pr-check-prod.yml
  hous-api/build.gradle
  hous-api/src/main/java/hous/api/ApiApplication.java
  hous-api/src/main/java/hous/api/service/auth/impl/AppleAuthService.java
  hous-api/src/main/java/hous/api/service/auth/impl/KakaoAuthService.java
  hous-api/src/main/java/hous/api/service/firebase/FirebaseCloudMessageService.java
  hous-external/build.gradle
  hous-external/src/main/java/hous/external/client/apple/AppleApiClient.java
  hous-external/src/main/java/hous/external/client/apple/AppleTokenProvider.java
  hous-external/src/main/java/hous/external/client/apple/AppleTokenProviderImpl.java
  hous-external/src/main/java/hous/external/client/apple/dto/response/ApplePublicKeyResponse.java
  hous-external/src/main/java/hous/external/client/firebase/FirebaseApiClient.java
  hous-external/src/main/java/hous/external/client/kakao/KakaoApiClient.java
  hous-external/src/main/java/hous/external/client/kakao/dto/response/KakaoProfileResponse.java
  settings.gradle
Labels: ✨ Feature, 🐼 혁준 🐼

#325 알림 및 배지 카운터 데이터를 mongodb로 마이그레이션 하는 일회성 api 추가
  hous-api/src/main/java/hous/api/controller/delete/MigrationController.java
  hous-api/src/main/java/hous/api/service/delete/MigrationService.java
  hous-api/src/main/java/hous/api/service/notification/dto/response/NotificationInfo.java
  hous-api/src/test/java/hous/api/service/migration/MigrationDataTest.java
  hous-common/src/main/java/hous/common/util/DateUtils.java
  hous-core/src/main/java/hous/core/domain/common/AuditingTimeEntity.java
  hous-core/src/main/java/hous/core/domain/delete/RdbNotification.java
  hous-core/src/main/java/hous/core/domain/delete/mysql/RdbNotificationRepository.java
  hous-core/src/main/java/hous/core/domain/notification/Notification.java
Labels: ✨ Feature, 🐣 혜정 🐣

#326 Notification content 및 배지 생성 시 푸시 메세지 만드는 로직 통일하고 코드 수정
  hous-api/src/main/java/hous/api/service/notification/NotificationService.java
  hous-api/src/test/java/hous/api/service/notification/NotificationServiceTest.java
Labels: 🐣 혜정 🐣, 🔧 Fix, 🔨 Refactor
